import assert from 'node:assert/strict';
import {test} from 'node:test';
import {z} from 'zod';
import {newStory,type Story,type Memory,mergeMemories,exportMarkdown,activeEntries} from '../lib/story/model';
import {workflow,type Step} from '../lib/story/workflow';
import type {ModelCall} from '../lib/story/ai';
const world={era:'架空王朝',rules:'武学不超越肉身',conflict:'门派争夺名册',tone:'冷峻江湖',boundaries:'不揭露妹妹藏身地'};
const hero={name:'林澈',identity:'弃徒',appearance:'右手旧伤',personality:'重义又怕失去归属',goal:'救妹妹',limits:'不会游泳',voice:'克制直率'};
const node={title:'交出名册',start:'傍晚渡口',content:'用名册换妹妹平安',motivation:'救妹妹',choice:'交出名册',result:'被逐出师门',cost:'失去庇护',preserve:'右手旧伤',forbidden:'妹妹藏身地',freedom:'可补充配角'};
const scenes=[{title:'渡口',blocks:[{type:'narration',speaker:'',content:'林澈交出了名册，被逐出师门。'}]}];
const changes=[{id:'ledger-owner',kind:'fact',content:'名册由阿宁持有',status:'active',source:'',evidence:'林澈将名册交给阿宁'},{id:'blue-seal',kind:'thread',content:'信封有蓝印章',status:'active',source:'',evidence:'信封上的印章尚未解开'}];
const immediate:Step=async(_name,work)=>work();
function fake(overrides:Record<string,unknown>={}):ModelCall{return async<T>(role:string,_prompt:string,schema:z.ZodType<T>)=>schema.parse(overrides[role]??({'世界观引导 Agent':{world,questions:[]},'人物 Agent':{hero,npcs:[{...hero,name:'阿宁'}]},'主角引导 Agent':{reply:'这一次你愿意付出师门的代价吗？',node},'正文 Agent':{scenes,changes,anchor:'渡口，名册已交出',question:''},'一致性检查':{ok:true,issues:[]},'章节 Agent':{title:'渡口诀别'},'摘要 Agent':{summary:'林澈为救妹妹交出名册，被逐出师门。',anchor:'渡口，林澈仍未决定是否登船',discussion:'下一事件尚未确认',retainedIds:['ledger-owner','blue-seal']},'记忆校验':{ok:true,issues:[]},'正文润色 Agent':{scenes},'讨论摘要 Agent':{summary:'作者确认右手旧伤，当前代价尚待决定'}} as Record<string,unknown>)[role]);}
async function ready(){let s=newStory('story','一个弃徒送信给仇家的江湖');s=await workflow(s,'world',{text:s.idea},fake(),immediate);s=await workflow(s,'confirmWorld',world,fake(),immediate);s=await workflow(s,'hero',{},fake(),immediate);s=await workflow(s,'confirmHero',{hero,npcs:s.npcs},fake(),immediate);return s;}
async function written(){let s=await ready();s=await workflow(s,'discuss',{text:'让他交出名册，被师门逐出'},fake(),immediate);s=await workflow(s,'confirmNode',node,fake(),immediate);return workflow(s,'write',{},fake(),immediate);}
test('gates prevent unconfirmed world, hero, and node writes',async()=>{const s=newStory('a','一个江湖故事');await assert.rejects(workflow(s,'hero',{},fake(),immediate),/确认世界/);await assert.rejects(workflow(s,'write',{},fake(),immediate),/先确认/);});
test('complete workflow separates author discussion and confirmed plan from facts',async()=>{let s=await ready();assert.equal(s.npcs[0].name,'阿宁');s=await workflow(s,'discuss',{text:'交出名册'},fake(),immediate);assert.equal(s.memories.length,0);assert.equal(s.entries.length,0);s=await workflow(s,'confirmNode',node,fake(),immediate);assert.equal(s.entries.length,0);assert.equal(s.nodeConfirmed,true);s=await workflow(s,'write',{},fake(),immediate);assert.equal(s.entries.length,1);assert.equal(s.memories.length,2);assert.equal(s.node,null);assert.equal(s.hero?.limits,'不会游泳');assert.ok(s.entries[0].skill.length===40);});
test('failed validation never mutates original story',async()=>{let s=await ready();s=await workflow(s,'confirmNode',node,fake(),immediate);const before=JSON.stringify(s);await assert.rejects(workflow(s,'write',{},fake({'一致性检查':{ok:false,issues:['缺少节点代价']}}),immediate),/缺少节点代价/);assert.equal(JSON.stringify(s),before);});
test('unresolved author question returns to confirmation without producing events',async()=>{const s=await workflow(await ready(),'confirmNode',node,fake(),immediate);const next=await workflow(s,'write',{},fake({'正文 Agent':{scenes:[],changes:[],anchor:'',question:'是否允许师父死亡？'}}),immediate);assert.equal(next.nodeConfirmed,false);assert.equal(next.entries.length,0);assert.match(next.chat.at(-1)!.text,/师父/);});
test('three compactions preserve facts, thread, characters, full conversation and pending node',async()=>{let s=await written();for(let i=0;i<3;i++){if(i){const next={...s.entries[0],id:`entry-${i}`,created:Date.now()};s.entries.push(next);}s.node=node;s.nodeId='pending';const transcript=JSON.stringify(s.conversation);s=await workflow(s,'archive',{},fake(),immediate);assert.equal(s.memories.length,2);assert.equal(s.memories[1].status,'active');assert.equal(s.hero?.limits,'不会游泳');assert.deepEqual(s.node,node);assert.equal(JSON.stringify(s.conversation),transcript);}assert.equal(s.chapters.length,3);assert.equal(activeEntries(s).length,0);});
test('missing mandatory memory ids prevents switching snapshot',async()=>{const s=await written();await assert.rejects(workflow(s,'archive',{},fake({'摘要 Agent':{summary:'简短',anchor:'渡口',discussion:'待定',retainedIds:[]}}),immediate),/遗漏/);assert.equal(s.chapters.length,0);});
test('discussion-only compaction does not invent a chapter or lose raw dialogue',async()=>{const s=await workflow(await ready(),'discuss',{text:'他要付出什么？'},fake(),immediate);const result=await workflow(s,'archive',{},fake(),immediate);assert.equal(result.chapters.length,0);assert.deepEqual(result.conversation,s.conversation);assert.deepEqual(result.node,s.node);});
test('checkpoint retry skips successful chapter while retrying failed summary',async()=>{const cache:Record<string,unknown>={};const counts:Record<string,number>={};const step:Step=async(name,fn)=>{if(Object.hasOwn(cache,name))return cache[name] as Awaited<ReturnType<typeof fn>>;counts[name]=(counts[name]||0)+1;const result=await fn();cache[name]=result;return result;};const s=await written();const failModel:ModelCall=async(role,prompt,schema,example)=>{if(role==='摘要 Agent')throw new Error('network');return fake()(role,prompt,schema,example);};await assert.rejects(workflow(s,'archive',{},failModel,step));const result=await workflow(s,'archive',{},fake(),step);assert.equal(result.chapters.length,1);assert.equal(counts.chapter,1);assert.equal(counts.memory,2);});
test('revision replays facts before removed event instead of retaining overwritten final state',async()=>{let s=await written();const later={...s.entries[0],id:'later',changes:[{...s.memories[0],content:'名册回到林澈手中',evidence:'阿宁归还名册'}]};s.entries.push(later);s.memories=mergeMemories(s.memories,later.changes,'later');const result=await workflow(s,'revise',{entryId:'later',world,hero,npcs:[]},fake(),immediate);assert.equal(result.memories.find(m=>m.id==='ledger-owner')?.content,'名册由阿宁持有');assert.equal(result.entries.length,1);assert.equal(s.entries.length,2);});
test('new memory cannot be born resolved; old facts need evidence',()=>{assert.throws(()=>mergeMemories([],[{...changes[0],status:'resolved'} as Memory],'e'),/有效/);assert.throws(()=>mergeMemories([changes[0] as Memory],[{...changes[0],evidence:''} as Memory],'e'),/依据/);});
test('export contains archived and active prose once; plans remain separate',async()=>{let s=await written();s=await workflow(s,'archive',{},fake(),immediate);s.entries.push({...s.entries[0],id:'new',scenes:[{title:'山路',blocks:[{type:'narration',speaker:'',content:'林澈走上山路。'}]}]});s.node=node;const md=exportMarkdown(s);assert.equal(md.split('林澈交出了名册，被逐出师门。').length-1,1);assert.match(md,/林澈走上山路/);assert.match(md,/当前事件方案（尚未发生）/);});
test('rewrite requires semantic validation and explicit acceptance',async()=>{const s=await written();const candidate=await workflow(s,'rewrite',{entryId:s.entries[0].id,text:'减少重复'},fake(),immediate);assert.ok(candidate.rewrite);assert.deepEqual(candidate.entries,s.entries);const accepted=await workflow(candidate,'acceptRewrite',{},fake(),immediate);assert.equal(accepted.rewrite,null);});
test('new discussion invalidates an earlier confirmation before writing',async()=>{let s=await workflow(await ready(),'confirmNode',node,fake(),immediate);s=await workflow(s,'discuss',{text:'改变一下刚才的代价'},fake({'主角引导 Agent':{reply:'要改变成什么代价？',node:null}}),immediate);assert.equal(s.nodeConfirmed,false);await assert.rejects(workflow(s,'write',{},fake(),immediate),/确认/);});
