import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const base=process.env.MANXIANG_TEST_URL||'http://localhost:5173';
let cookie='';
async function api(path='',body,auth=true){const response=await fetch(base+'/api/stories'+path,{method:body?'POST':'GET',headers:{...(auth&&cookie?{cookie}:{}),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});if(auth&&response.headers.get('set-cookie'))cookie=response.headers.get('set-cookie').split(';')[0];return {status:response.status,data:await response.json()};}
const world={era:'架空王朝',rules:'普通武学',conflict:'名册争夺',tone:'冷峻',boundaries:'不暴露妹妹身份'};
const hero={name:'林澈',identity:'弃徒',appearance:'右手旧伤',personality:'克制',goal:'救妹妹',limits:'不会游泳',voice:'直率'};
const node={title:'交出名册',start:'渡口',content:'以名册救妹妹',motivation:'亲情',choice:'交名册',result:'离开师门',cost:'失去庇护',preserve:'旧伤',forbidden:'妹妹身份',freedom:'可补充试探'};
const list=await api();assert.equal(list.status,200);
const id=crypto.randomUUID();
const created=await api('',{action:'create',payload:{idea:'自动验证：不会使用付费模型'},requestId:id});assert.equal(created.status,200);
await writeFile('/private/tmp/manxiang-smoke-cleanup.sql',`DELETE FROM story_runs WHERE story='${id}';\nDELETE FROM story_revisions WHERE story='${id}';\nDELETE FROM stories WHERE id='${id}';\n`);
assert.equal((await api('?id='+id,undefined,false)).status,404);
const command={id,version:0,requestId:crypto.randomUUID(),action:'confirmWorld',payload:world};
const confirmed=await api('',command);assert.equal(confirmed.status,200);assert.equal(confirmed.data.story.version,1);
assert.equal((await api('',command)).data.story.version,1);
assert.equal((await api('',{...command,requestId:crypto.randomUUID()})).status,409);
const heroResult=await api('',{id,version:1,requestId:crypto.randomUUID(),action:'confirmHero',payload:{hero,npcs:[]}});assert.equal(heroResult.status,200);
const nodeResult=await api('',{id,version:2,requestId:crypto.randomUUID(),action:'confirmNode',payload:node});assert.equal(nodeResult.status,200);assert.equal(nodeResult.data.story.entries.length,0);assert.equal(nodeResult.data.story.memories.length,0);
const failed=await api('',{id,version:3,requestId:crypto.randomUUID(),action:'write',payload:{}});assert.equal(failed.status,401);
const saved=await api('?id='+id);assert.equal(saved.data.story.version,3);assert.equal(saved.data.run.status,'failed');
const competing=await Promise.all([api('',{id,version:3,requestId:crypto.randomUUID(),action:'confirmNode',payload:node}),api('',{id,version:3,requestId:crypto.randomUUID(),action:'confirmNode',payload:node})]);assert.deepEqual(competing.map(x=>x.status).sort(),[200,409]);
const exported=await api('?id='+id+'&format=json');assert.equal(exported.status,200);assert.equal(exported.data.formatVersion,1);assert.equal(exported.data.story.version,4);
const old=await api('?id='+id+'&format=json&revision=0');assert.equal(old.status,200);assert.equal(old.data.story.worldConfirmed,false);
assert.equal((await api('?id='+id+'&revision=0',undefined,false)).status,404);
console.log('API verified: server persistence, ownership isolation, idempotency, stale/concurrent version rejection, failure lock release, pending-plan isolation, exports and history. No paid model call made.');
