"use client";
import {useEffect,useRef,useState} from "react";
import {ArrowRight,BookOpen,Check,Download,Feather,History,LoaderCircle,Plus,RefreshCw,Settings2,Sparkles,Users} from "lucide-react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {NativeSelect,NativeSelectOption} from "@/components/ui/native-select";
import {Toaster} from "@/components/ui/sonner";
import {toast} from "sonner";
import {type Story,type World,type Hero,type Node,activeEntries,blocksText,contextBytes,INPUT_BUDGET,needsArchive} from "@/lib/story/model";
import type {Action} from "@/lib/story/workflow";
import "./novel.css";
const labels:Record<string,string>={era:"时代与地域",rules:"世界规则与武学边界",conflict:"核心冲突",tone:"故事基调",boundaries:"作者禁区与偏好",name:"姓名",identity:"身份",appearance:"外貌与特征",personality:"性格与矛盾",goal:"目标与恐惧",limits:"能力与限制",voice:"说话方式",title:"事件标题",start:"事件起点",content:"主要内容",motivation:"人物动机",choice:"关键选择",result:"预期结果",cost:"付出的代价",preserve:"必须保留",forbidden:"不可改变 / 暂不揭示",freedom:"可自由扩写范围"};
const emptyWorld:World={era:"",rules:"",conflict:"",tone:"",boundaries:""};
type RunView={id:string;status:string;error:string|null;updated:number;steps:string[];command:{action:Action;payload:unknown;version:number}};
function Fields<T extends object>({value,onChange,disabled=false}:{value:T;onChange:(value:T)=>void;disabled?:boolean}){return <fieldset disabled={disabled} className="n-fields">{Object.entries(value).map(([field,text])=><label key={field}>{labels[field]||field}<textarea value={String(text)} rows={field==="content"?4:2} maxLength={field==="boundaries"||field==="preserve"||field==="forbidden"?3000:6000} onChange={e=>onChange({...value,[field]:e.target.value})}/></label>)}</fieldset>}
export default function Home(){
 const [stories,setStories]=useState<{id:string;title:string;version:number}[]>([]),[story,setStory]=useState<Story|null>(null),[tab,setTab]=useState("world"),[error,setError]=useState(""),[busy,setBusy]=useState("");
 const [idea,setIdea]=useState(""),[message,setMessage]=useState(""),[world,setWorld]=useState<World>(emptyWorld),[hero,setHero]=useState<Hero|null>(null),[npcs,setNpcs]=useState<Hero[]>([]),[node,setNode]=useState<Node|null>(null);
 const [provider,setProvider]=useState("deepseek");
 const [key,setKey]=useState(""),[keyInput,setKeyInput]=useState(""),[settings,setSettings]=useState(false),[newDialog,setNewDialog]=useState(false),[revisionDialog,setRevisionDialog]=useState(false),[revisionId,setRevisionId]=useState(""),[run,setRun]=useState<RunView|null>(null),[versions,setVersions]=useState<{version:number;created:number}[]>([]),[rewriteText,setRewriteText]=useState(""),[rewriteId,setRewriteId]=useState("");
 const working=useRef(false),draft=useRef(false);const current=useRef(story);current.current=story;
 const update=(s:Story)=>{setStory(s);setWorld(s.world||emptyWorld);setHero(s.hero);setNpcs(s.npcs);setNode(s.node);draft.current=false;};
 async function json(response:Response){const data=await response.json() as {error?:string;story?:Story;stories?:typeof stories;run?:RunView|null;versions?:typeof versions};if(!response.ok)throw new Error(data.error||"请求失败，请重试。");return data;}
 async function refreshList(){const data=await json(await fetch("/api/stories"));setStories(data.stories||[]);return data.stories||[];}
 async function open(id:string){const data=await json(await fetch(`/api/stories?id=${id}`));if(data.story){update(data.story);setRun(data.run||null);setVersions(data.versions||[]);setMessage("");setRewriteId(data.story.entries.at(-1)?.id||"");setTab(!data.story.worldConfirmed?"world":!data.story.heroConfirmed?"hero":"node");}}
 useEffect(()=>{refreshList().catch(e=>setError(String(e.message)));},[]);
 useEffect(()=>{const fn=(event:BeforeUnloadEvent)=>{if(working.current||draft.current){event.preventDefault();event.returnValue="";}};window.addEventListener("beforeunload",fn);return()=>window.removeEventListener("beforeunload",fn);},[]);
 async function command(action:Action|"create",payload:unknown,label:string,retry?:RunView){
  if(working.current)return;
  const modelActions=["world","hero","discuss","write","archive","rewrite"];
  if(modelActions.includes(action)&&!key){setKeyInput("");setSettings(true);return;}
  working.current=true;setBusy(label);setError("");
  const id=retry?.id||crypto.randomUUID(),version=retry?.command.version??story?.version;
  try{const data=await json(await fetch("/api/stories",{method:"POST",headers:{"Content-Type":"application/json","x-ai-key":key,"x-ai-provider":provider},body:JSON.stringify({action,payload,id:story?.id,version,requestId:id})}));if(data.story){update(data.story);const meta=await json(await fetch(`/api/stories?id=${data.story.id}`));setRun(meta.run||null);setVersions(meta.versions||[]);if(action==="create"){setNewDialog(false);setTab("world");}if(action==="confirmWorld")setTab("hero");if(action==="confirmHero"||action==="discuss")setTab("node");if(action==="write"||action==="rewrite"||action==="acceptRewrite"){setTab("novel");setRewriteId(data.story.entries.at(-1)?.id||"");}if(action==="archive")setTab("memory");if(action==="revise"){setRevisionDialog(false);setTab("node");}if(action==="discuss")setMessage("");toast.success("已保存");await refreshList();
   if(action==="write"&&needsArchive(data.story)){setBusy("正在自动整理章节与记忆…");const archived=await json(await fetch("/api/stories",{method:"POST",headers:{"Content-Type":"application/json","x-ai-key":key,"x-ai-provider":provider},body:JSON.stringify({action:"archive",payload:{},id:data.story.id,version:data.story.version,requestId:crypto.randomUUID()})}));if(archived.story)update(archived.story);}
  }}catch(e){setError(e instanceof Error?e.message:"任务失败");if(story){try{const data=await json(await fetch(`/api/stories?id=${story.id}`));setRun(data.run||null);}catch{}}}finally{working.current=false;setBusy("");}
 }
 const retry=()=>{if(run)void command(run.command.action,run.command.payload,"恢复上次任务…",run);};
 const go=(id:string)=>{setError("");void open(id).catch(e=>setError(e.message));};
 const exportUrl=(format:string,version?:number)=>`/api/stories?id=${story?.id}&format=${format}${version===undefined?"":`&revision=${version}`}`;
 const mark=<T,>(setter:(v:T)=>void)=>(v:T)=>{draft.current=true;setter(v);};
 return <div className="novel-app"><Toaster position="bottom-right"/><header className="n-top"><a className="n-brand" href="/"><span><Feather size={23}/></span><strong>漫想<small>江湖写作陪伴</small></strong></a><div className="n-top-actions"><a href="/comic">漫画工作台</a><button onClick={()=>{setKeyInput(key);setSettings(true);}} disabled={!!busy}><Settings2 size={16}/>{key?"AI 已配置":"连接 AI"}</button></div></header>
 <div className="n-shell"><aside className="n-side"><div className="n-side-heading"><span>我的江湖</span><button aria-label="创建故事" disabled={!!busy} onClick={()=>setNewDialog(true)}><Plus size={18}/></button></div><div className="n-stories">{stories.map(s=><button key={s.id} className={story?.id===s.id?"chosen":""} disabled={!!busy} onClick={()=>go(s.id)}><BookOpen size={17}/><span>{s.title}</span></button>)}{!stories.length&&<p>还没有故事。<br/>从一个念头开始。</p>}</div><div className="n-side-note">你是作者，<br/>故事的最终决定在你。<small>存档保存在服务端，通过当前浏览器续写。清除浏览器数据可能失去访问入口，请及时导出。</small></div></aside>
 <main className="n-main">{error&&<div className="n-error" role="alert">{error}<button onClick={()=>setError("")}>关闭</button></div>}{busy&&<div className="n-progress" role="status"><LoaderCircle className="spin" size={16}/>{busy}<span>完成的阶段会保存，刷新后可恢复。</span></div>}
 {!story?<section className="n-welcome"><div className="n-kicker">一念起，江湖生</div><h1>写一个<br/>属于你的江湖。</h1><p>先建世界，再识主角。<br/>与他商量命运，把每一次选择写成故事。</p><div className="n-start-card"><label htmlFor="new-idea">你想写怎样的故事？</label><textarea id="new-idea" value={idea} onChange={e=>setIdea(e.target.value)} maxLength={3000} placeholder="一个被逐出师门的少年，要将一封不能打开的信送给仇家……"/><button className="n-primary" disabled={!!busy||idea.trim().length<8} onClick={()=>command("create",{idea},"创建故事…")}>开启这段江湖<ArrowRight size={17}/></button></div><div className="n-workflow"><span>01 世界观</span><span>02 主角</span><span>03 重大事件</span><span>04 小说正文</span></div></section>:<>
 <div className="n-title"><div><span className="n-kicker">创作案头 · 版本 {story.version}</span><h1>{story.title}</h1></div><div className="n-title-actions"><button disabled={!!busy} onClick={()=>go(story.id)} aria-label="刷新存档"><RefreshCw size={16}/></button><a href={exportUrl("md")}><Download size={16}/>导出正文</a><a href={exportUrl("json")}>JSON</a></div></div>
 {run&&run.status!=="succeeded"&&!busy&&<div className="n-run"><div><strong>{run.status==="running"?"上次任务仍在处理":"上次任务未完成"}</strong><p>{run.error||"可以刷新查看结果；锁超时后可以恢复原任务。"}</p><small>已保存阶段：{run.steps.join(" → ")||"暂无"}</small></div><button onClick={retry}>恢复原任务</button></div>}
 <Tabs value={tab} onValueChange={setTab}><TabsList className="n-tabs" variant="line"><TabsTrigger value="world">世界观 {story.worldConfirmed&&<Check size={13}/>}</TabsTrigger><TabsTrigger value="hero">主角 {story.heroConfirmed&&<Check size={13}/>}</TabsTrigger><TabsTrigger value="node">重大事件</TabsTrigger><TabsTrigger value="novel">小说正文</TabsTrigger><TabsTrigger value="memory">章节与记忆</TabsTrigger></TabsList>
 <TabsContent value="world"><section className="n-panel"><div className="n-section-title"><div><h2>先定江湖的规矩</h2><p>时代、规则、冲突与基调，由你确认。</p></div><span>{story.worldConfirmed?"已确认":"草案"}</span></div>{!story.worldConfirmed&&<div className="n-prompt"><label>补充你的世界设想<textarea value={message} onChange={e=>setMessage(e.target.value)} maxLength={6000} placeholder="不确定的地方，让助手提出建议。"/></label><button className="n-secondary" disabled={!!busy} onClick={()=>command("world",{text:message||story.idea},"正在构思世界观…")}><Sparkles size={16}/>{story.world?"根据补充调整草案":"生成世界观草案"}</button></div>}{story.chat.length>0&&!story.worldConfirmed&&<p className="n-guidance">{story.chat.at(-1)?.text}</p>}<Fields value={world} onChange={mark(setWorld)} disabled={!!busy||story.worldConfirmed}/>{!story.worldConfirmed?<button className="n-primary" disabled={!!busy||![world.era,world.rules,world.conflict,world.tone].every(s=>s.trim())} onClick={()=>command("confirmWorld",world,"保存世界观…")}>确认世界观<ArrowRight size={16}/></button>:<button className="n-secondary" disabled={!!busy||!hero} onClick={()=>{setRevisionId(story.entries[0]?.id||"");setRevisionDialog(true);}}>修订设定与故事</button>}</section></TabsContent>
 <TabsContent value="hero"><section className="n-panel"><div className="n-section-title"><div><h2>他是谁，又为何踏入江湖？</h2><p>人物可以质疑和追问，最终由你决定。</p></div><Users size={24}/></div>{!story.worldConfirmed?<p>先确认世界观，再生成主角。</p>:<>{!story.heroConfirmed&&<button className="n-secondary" disabled={!!busy} onClick={()=>command("hero",{},"正在设计人物…")}><Sparkles size={16}/>{hero?"重新设计人物":"生成主角与主要配角"}</button>}{hero&&<><h3 className="n-subtitle">主角</h3><Fields value={hero} onChange={mark(setHero)} disabled={!!busy||story.heroConfirmed}/>{npcs.map((npc,i)=><details key={i} className="n-details"><summary>配角 · {npc.name}</summary><Fields value={npc} disabled={!!busy||story.heroConfirmed} onChange={value=>{draft.current=true;setNpcs(npcs.map((n,j)=>j===i?value:n));}}/></details>)}{!story.heroConfirmed&&<button className="n-primary" disabled={!!busy} onClick={()=>command("confirmHero",{hero,npcs},"保存人物设定…")}>确认人物，开始讨论<ArrowRight size={16}/></button>}</>}</>}</section></TabsContent>
 <TabsContent value="node"><div className="n-node-layout"><section className="n-panel n-conversation"><div className="n-section-title"><div><h2>与{story.hero?.name||"主角"}商量命运</h2><p>这是创作讨论，不会直接变成小说对白。</p></div></div><div className="n-messages">{story.chat.map((m,i)=><div key={i} className={`n-message ${m.role}`}><span>{m.role==="author"?"你 · 作者":story.hero?.name||"引导助手"}</span><p>{m.text}</p></div>)}{!story.chat.length&&<p className="n-empty">告诉主角，这一次你希望发生什么。无需先想好全书。</p>}</div><label className="n-compose">下一件大事<textarea disabled={!story.heroConfirmed||!!busy} value={message} onChange={e=>{draft.current=true;setMessage(e.target.value);}} maxLength={6000} placeholder="让他为救妹妹交出名册，被逐出师门。但暂不暴露妹妹的身份。"/></label><button className="n-primary" disabled={!!busy||!story.heroConfirmed||!message.trim()} onClick={()=>command("discuss",{text:message},"主角正在整理事件与追问…")}>与主角讨论<ArrowRight size={16}/></button></section><section className="n-panel n-node-card"><div className="n-section-title"><div><h2>当前事件卡</h2><p>{story.nodeConfirmed?"方案已确认，正文尚未发生。":"动机、选择、结果与代价，想清楚再落笔。"}</p></div></div>{node?<><Fields value={node} onChange={mark(setNode)} disabled={!!busy}/><div className="n-button-stack"><button className="n-secondary" disabled={!!busy} onClick={()=>command("confirmNode",node,"确认节点方案…")}>确认 / 更新事件方案</button><button className="n-primary" disabled={!!busy||!story.nodeConfirmed||JSON.stringify(node)!==JSON.stringify(story.node)} onClick={()=>command("write",{},"正在加载金庸 skill 并扩写正文…")}><Feather size={16}/>把这个节点写成小说</button></div></>:<div className="n-empty">讨论清楚主要事件后，主角会在这里提出节点草案。<p>也可以直接提供完整事件，跳过多余追问。</p></div>}</section></div></TabsContent>
 <TabsContent value="novel"><section className="n-panel"><div className="n-section-title"><div><h2>落笔成章</h2><p>{story.entries.length} 个事件已写入 · {story.chapters.length} 个章节已归档</p></div><button className="n-secondary" disabled={!!busy||!story.entries.length} onClick={()=>command("archive",{},"正在归档章节、更新记忆…")}>整理章节</button></div>{!story.entries.length&&<p className="n-empty">先确认一个重大事件，正文会从这里开始。</p>}{story.entries.map((entry,i)=><article className="n-prose" key={entry.id}><span className="n-kicker">事件 {String(i+1).padStart(2,"0")} · {story.chapters.find(c=>c.entryIds.includes(entry.id))?.title||"未归档草稿"}</span><h2>{entry.node.title}</h2>{entry.scenes.map((scene,j)=><section key={j}><h3>{scene.title}</h3>{scene.blocks.map((block,k)=><p key={k}>{block.type==="dialogue"?`${block.speaker}：${block.content}`:block.content}</p>)}</section>)}<button className="n-text-button" disabled={!!busy} onClick={()=>setRewriteId(entry.id)}>选择此段润色</button></article>)}{story.entries.length>0&&<div className="n-rewrite"><h3>局部改写</h3><NativeSelect aria-label="改写事件" value={rewriteId} onChange={e=>setRewriteId(e.target.value)}>{story.entries.map(e=><NativeSelectOption value={e.id} key={e.id}>{e.node.title}</NativeSelectOption>)}</NativeSelect><textarea value={rewriteText} onChange={e=>setRewriteText(e.target.value)} maxLength={4000} placeholder="减少重复回忆，增强交出名册之前的试探。"/><button className="n-secondary" disabled={!!busy||!rewriteText.trim()||!rewriteId} onClick={()=>command("rewrite",{entryId:rewriteId,text:rewriteText},"正在生成改写候选并核对事实…")}>生成改写候选</button>{story.rewrite&&<div className="n-candidate"><h4>待接受的改写</h4><pre>{blocksText(story.rewrite.scenes)}</pre><button className="n-primary" disabled={!!busy} onClick={()=>command("acceptRewrite",{},"保存改写…")}>接受改写</button><button className="n-secondary" disabled={!!busy} onClick={()=>command("discardRewrite",{},"保留原作…")}>保留原作</button></div>}</div>}</section></TabsContent>
 <TabsContent value="memory"><section className="n-panel"><div className="n-section-title"><div><h2>江湖有迹，前事不忘</h2><p>人物卡与事实独立保留，摘要只整理表达。</p></div><History size={24}/></div><div className="n-memory-stats"><span>{story.memories.filter(m=>m.status==="active").length}<small>有效记忆</small></span><span>{story.memories.filter(m=>m.kind==="thread"&&m.status==="active").length}<small>未解伏笔</small></span><span>{Math.min(100,Math.round(contextBytes(story)/INPUT_BUDGET*100))}%<small>保守上下文预算</small></span></div><button className="n-secondary" disabled={!!busy} onClick={()=>command("archive",{},"正在整理章节与记忆…")}>立即整理{activeEntries(story).length?"章节":"创作讨论"}</button><h3 className="n-subtitle">上一章摘要</h3><p className="n-summary">{story.summary||"完成章节整理后显示。"}</p><p className="n-anchor">当前衔接：{story.anchor||"尚未开始正文"}</p>{story.chapters.map((c,i)=><details className="n-details" key={c.id}><summary>第 {i+1} 章 · {c.title}</summary><p>{c.summary}</p><small>{c.entryIds.length} 个事件 · {c.status==="ready"?"记忆已更新":"记忆待更新"}</small></details>)}<h3 className="n-subtitle">事实、承诺与伏笔</h3>{story.memories.map(m=><div key={m.id} className="n-memory"><span>{m.kind==="thread"?"伏笔":m.kind==="promise"?"承诺":"事实"} · {m.status==="active"?"有效":m.status==="resolved"?"已解决":"已替代"}</span><p>{m.content}</p><small>{m.id} · 来源 {m.source}</small></div>)}<h3 className="n-subtitle">历史快照</h3><p>修订保留之前的完整作品，可以导出查看。</p><div className="n-version-list">{versions.map(v=><a href={exportUrl("json",v.version)} key={v.version}>版本 {v.version} <Download size={13}/></a>)}</div><button className="n-secondary" disabled={!!busy||!hero} onClick={()=>{setRevisionId(story.entries[0]?.id||"");setRevisionDialog(true);}}>修订设定或重大事件</button></section></TabsContent>
 </Tabs></>}
 </main></div><Dialog open={settings} onOpenChange={setSettings}><DialogContent><DialogHeader><DialogTitle>连接 AI</DialogTitle><DialogDescription>选择 AI 服务并填写对应 API Key。Key 仅保留在页面内存，不写入存档；故事资料经本站转发给所选服务，生成按你的 API 账户计费。</DialogDescription></DialogHeader><form className="n-dialog-form" onSubmit={e=>{e.preventDefault();setKey(keyInput.trim());setKeyInput("");setSettings(false);toast("已配置，首次生成时验证权限。");}}><label>AI 服务<NativeSelect value={provider} onChange={e=>{setProvider(e.target.value);setKey("");setKeyInput("");}}><NativeSelectOption value="deepseek">DeepSeek</NativeSelectOption><NativeSelectOption value="openai">OpenAI</NativeSelectOption></NativeSelect></label><label>{provider==="deepseek"?"DeepSeek":"OpenAI"} API Key<input type="password" minLength={20} maxLength={500} required autoComplete="off" value={keyInput} onChange={e=>setKeyInput(e.target.value)}/></label><small>文本模型：{provider==="deepseek"?"DeepSeek Flash":"GPT-4.1 mini"} · 正文使用固定版本金庸 skill</small><button className="n-primary">保存配置</button>{key&&<button type="button" className="n-secondary" onClick={()=>{setKey("");setKeyInput("");setSettings(false);}}>清除配置</button>}</form></DialogContent></Dialog>
 <Dialog open={newDialog} onOpenChange={setNewDialog}><DialogContent><DialogHeader><DialogTitle>新建一段江湖</DialogTitle><DialogDescription>至少写下 8 个字。助手会引导你补齐世界观。</DialogDescription></DialogHeader><textarea value={idea} onChange={e=>setIdea(e.target.value)} maxLength={3000}/><button className="n-primary" disabled={!!busy||idea.trim().length<8} onClick={()=>command("create",{idea},"创建故事…")}>创建故事</button></DialogContent></Dialog>
 <Dialog open={revisionDialog} onOpenChange={setRevisionDialog}><DialogContent className="n-revision-dialog"><DialogHeader><DialogTitle>修订设定与故事起点</DialogTitle><DialogDescription>保留旧版本快照，从选定事件起移除其后正文、章节和相关记忆，再按新设定重新创作。此操作不会假装下游已经同步改写。</DialogDescription></DialogHeader>{story&&hero&&<><label>修订起点<NativeSelect value={revisionId} onChange={e=>setRevisionId(e.target.value)}><NativeSelectOption value="">尚未有正文时，仅修改设定</NativeSelectOption>{story.entries.map((e,i)=><NativeSelectOption key={e.id} value={e.id}>从事件 {i+1}「{e.node.title}」重新写</NativeSelectOption>)}</NativeSelect></label><p className="n-notice">将移出当前版本：{revisionId?story.entries.length-story.entries.findIndex(e=>e.id===revisionId):0} 个事件。旧版本可在“章节与记忆”中导出。</p><details open><summary>世界设定</summary><Fields value={world} onChange={setWorld}/></details><details><summary>主角设定</summary><Fields value={hero} onChange={setHero}/></details>{npcs.map((npc,i)=><details key={i}><summary>配角 · {npc.name}</summary><Fields value={npc} onChange={value=>setNpcs(npcs.map((n,j)=>j===i?value:n))}/></details>)}<button className="n-primary" disabled={!!busy} onClick={()=>command("revise",{entryId:revisionId||null,world,hero,npcs},"建立修订版本…")}>确认影响并建立修订起点</button></>}</DialogContent></Dialog>
 </div>;
}
