import { z } from "zod";
const text=z.string().trim().min(1).max(6000);
export const worldSchema=z.object({era:text,rules:text,conflict:text,tone:text,boundaries:z.string().max(3000)});
export const heroSchema=z.object({name:text,identity:text,appearance:text,personality:text,goal:text,limits:text,voice:text});
export const nodeSchema=z.object({title:text,start:text,content:text,motivation:text,choice:text,result:text,cost:text,preserve:z.string().max(3000),forbidden:z.string().max(3000),freedom:text});
export const memorySchema=z.object({id:z.string().max(100),kind:z.enum(["fact","thread","promise"]),content:text,status:z.enum(["active","resolved","superseded"]),source:z.string().max(100),evidence:z.string().max(3000)});
export const sceneSchema=z.object({title:text,blocks:z.array(z.object({type:z.enum(["action","dialogue","narration"]),speaker:z.string().max(100),content:text})).min(1).max(40)});
export type World=z.infer<typeof worldSchema>;export type Hero=z.infer<typeof heroSchema>;export type Node=z.infer<typeof nodeSchema>;export type Memory=z.infer<typeof memorySchema>;export type Scene=z.infer<typeof sceneSchema>;
export type Entry={id:string;nodeId:string;node:Node;scenes:Scene[];memories:string[];changes:Memory[];skill:string;created:number};
export type Chapter={id:string;title:string;entryIds:string[];status:"archived"|"ready";summary:string};
export type Story={id:string;title:string;version:number;idea:string;world:World|null;worldConfirmed:boolean;worldVersion:number;hero:Hero|null;npcs:Hero[];heroConfirmed:boolean;heroVersion:number;node:Node|null;nodeId:string|null;nodeConfirmed:boolean;chat:{role:"author"|"hero";text:string}[];conversation:{role:"author"|"hero";text:string}[];entries:Entry[];chapters:Chapter[];memories:Memory[];summary:string;anchor:string;revision:number;rewrite:{entryId:string;scenes:Scene[]}|null;updated:number};
export const newStory=(id:string,idea:string):Story=>({id,title:idea.slice(0,24),version:0,idea,world:null,worldConfirmed:false,worldVersion:0,hero:null,npcs:[],heroConfirmed:false,heroVersion:0,node:null,nodeId:null,nodeConfirmed:false,chat:[],conversation:[],entries:[],chapters:[],memories:[],summary:"",anchor:"",revision:0,rewrite:null,updated:Date.now()});
export class StoryError extends Error{constructor(message:string,public status=400){super(message);}}
export function requireState(condition:unknown,message:string):asserts condition{if(!condition)throw new StoryError(message);}
export function blocksText(scenes:Scene[]){return scenes.map(s=>`### ${s.title}\n\n${s.blocks.map(b=>b.type==="dialogue"?`${b.speaker}：${b.content}`:b.content).join("\n\n")}`).join("\n\n");}
export function mergeMemories(old:Memory[],changes:Memory[],source:string){const map=new Map(old.map(m=>[m.id,m]));for(const c of changes){requireState(c.content.trim(),"记忆内容不能为空");if(map.has(c.id))requireState(c.evidence.trim(),"更改既有事实须有明确事件依据");else requireState(c.status==="active","新记忆必须处于有效状态");map.set(c.id,{...c,source});}return [...map.values()];}
export function activeEntries(s:Story){const archived=new Set(s.chapters.flatMap(c=>c.entryIds));return s.entries.filter(e=>!archived.has(e.id));}
export function context(s:Story){return {world:s.world,hero:s.hero,npcs:s.npcs,worldVersion:s.worldVersion,heroVersion:s.heroVersion,node:s.node,summary:s.summary,anchor:s.anchor,memories:s.memories,active:activeEntries(s).map(e=>({id:e.id,node:e.node,scenes:e.scenes})),discussion:s.chat.slice(-12)};}
// Conservative UTF-8 byte upper bound, including output reserve. Avoids undercounting Chinese.
export function contextBytes(s:Story){return new TextEncoder().encode(JSON.stringify(context(s))).length;}
export const INPUT_BUDGET=70000;
export function needsArchive(s:Story){return contextBytes(s)>INPUT_BUDGET*.7&&activeEntries(s).length>0;}
export function ensureBudget(s:Story,extra=0){requireState(contextBytes(s)+extra<INPUT_BUDGET*.85,"上下文接近上限，请先整理章节；若仍超限，请精简世界或当前节点描述。");}
export function exportMarkdown(s:Story){const byId=new Map(s.entries.map(e=>[e.id,e]));const chapters=s.chapters.map((c,i)=>`## 第${i+1}章 ${c.title}\n\n${c.entryIds.map(id=>byId.get(id)).filter((e):e is Entry=>!!e).map(e=>blocksText(e.scenes)).join("\n\n")}\n\n> 记忆状态：${c.status==="ready"?"已更新":"待更新"}\n${c.summary}`).join("\n\n");return `# ${s.title}\n\n版本：${s.version} · 导出：${new Date().toISOString()}\n\n## 世界观${s.worldConfirmed?"":"（草案）"}\n${s.world?Object.entries(s.world).map(([k,v])=>`${k}：${v}`).join("\n\n"):"尚未生成"}\n\n## 主角${s.heroConfirmed?"":"（草案）"}\n${s.hero?Object.entries(s.hero).map(([k,v])=>`${k}：${v}`).join("\n\n"):"尚未生成"}\n\n${chapters}\n\n## 当前未归档正文\n\n${activeEntries(s).map(e=>blocksText(e.scenes)).join("\n\n")}\n\n## 当前事件方案（尚未发生）\n${s.node?Object.entries(s.node).map(([k,v])=>`${k}：${v}`).join("\n\n"):"尚未建立"}\n\n## 事实与伏笔\n${s.memories.map(m=>`- [${m.status}] ${m.content}（${m.id}，来源 ${m.source}）`).join("\n")}\n\n## 创作讨论（非小说对白）\n${s.conversation.map(c=>`${c.role==="author"?"作者":"主角"}：${c.text}`).join("\n\n")}`;}
