"use client";

import { useEffect, useRef, useState } from "react";
import { ArrowRight, BookOpen, Check, Clapperboard, Download, Feather, ImageIcon, LoaderCircle, LockKeyhole, RefreshCw, Settings2, Sparkles, Users, WandSparkles } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Progress } from "@/components/ui/progress";
import { Toaster } from "@/components/ui/sonner";
import { toast } from "sonner";
import { styles, sampleProject, sampleStory, type Project, type Character, type Panel, planSchema, imageResponseSchema } from "@/lib/comic";
import { exportComic, exportScript } from "@/lib/export";

type Tab="script"|"characters"|"panels"|"comic";
const stages=[{id:"script",label:"剧本",Icon:BookOpen},{id:"characters",label:"角色",Icon:Users},{id:"panels",label:"分镜",Icon:Clapperboard},{id:"comic",label:"漫画",Icon:ImageIcon}] as const;

export default function Home(){
 const [story,setStory]=useState("");const [style,setStyle]=useState<string>(styles[0]);const [count,setCount]=useState("4");
 const [project,setProject]=useState<Project|null>(null);const [tab,setTab]=useState<Tab>("script");
 const [key,setKey]=useState("");const [draftKey,setDraftKey]=useState("");const [settings,setSettings]=useState(false);
 const [busy,setBusy]=useState("");const [error,setError]=useState("");const [progress,setProgress]=useState<{done:number;total:number}|null>(null);
 const busyRef=useRef(false),stopRef=useRef(false);const projectRef=useRef(project);projectRef.current=project;
 const loaded=project?.panels.filter(p=>p.image&&!p.stale).length||0;
 const needKey=()=>{if(key)return false;setSettings(true);return true;};
 const run=async(label:string,fn:()=>Promise<void>)=>{if(busyRef.current)return;busyRef.current=true;stopRef.current=false;setBusy(label);setError("");try{await fn();}catch(e){setError(e instanceof Error?e.message:"操作失败，请重试。");}finally{busyRef.current=false;setBusy("");setProgress(null);}};
 async function request(body:object){const response=await fetch("/api/create",{method:"POST",headers:{"Content-Type":"application/json","x-openai-key":key},body:JSON.stringify(body)});let data;try{data=await response.json();}catch{throw new Error("服务未返回完整结果，请稍后重试。");}if(!response.ok)throw new Error(typeof data==="object"&&data&&"error" in data&&typeof data.error==="string"?data.error:"生成失败，请重试。");return data;}
 function loadSample(){if(busyRef.current)return;setStory(sampleStory);setStyle(styles[0]);setCount("4");setProject(sampleProject());setTab("script");setError("");toast("已载入示例剧本、角色、分镜与首格插画");}
 async function createPlan(){if(story.trim().length<8){setError("请至少写下 8 个字，让故事有一个起点。");return;}if(needKey())return;await run("正在创作剧本、角色与分镜…",async()=>{const data=planSchema.parse(await request({action:"plan",story,style,count:Number(count)}));setProject({...data,style,demo:false});setTab("script");toast.success("创作方案已完成，可以逐步调整，也可以直接绘制漫画。");});}
 function changeCharacter(index:number,field:keyof Character,value:string){setProject(p=>p?{...p,referenceStale:!!p.reference,characters:p.characters.map((c,i)=>i===index?{...c,[field]:value}:c),panels:p.panels.map(s=>({...s,stale:!!s.image}))}:p);}
 function changePanel(index:number,field:keyof Pick<Panel,"title"|"shot"|"scene"|"dialogue">,value:string){setProject(p=>p?{...p,panels:p.panels.map((s,i)=>i===index?{...s,[field]:value,stale:field==="dialogue"?s.stale:!!s.image}:s)}:p);}
 async function rebreak(){if(!project||needKey())return;const source=project;await run("正在按当前剧本更新分镜…",async()=>{const data=planSchema.pick({panels:true}).parse(await request({action:"panels",script:source.script,characters:source.characters,style:source.style,count:Number(count)}));setProject({...source,panels:data.panels,boardStale:false});setTab("panels");toast.success("分镜已按当前剧本更新");});}
 async function makeReference(p:Project):Promise<Project>{const result=imageResponseSchema.parse(await request({action:"reference",style:p.style,characters:p.characters}));const next={...p,reference:result.image,referenceStale:false,panels:p.panels.map(s=>({...s,stale:!!s.image}))};setProject(next);return next;}
 async function referenceOnly(){if(!project||needKey())return;const source=project;await run("正在绘制角色参考图，可能需要一两分钟…",async()=>{await makeReference(source);toast.success("角色参考图已更新，后续画面将沿用这张设定图。");});}
 async function draw(index?:number){if(!project||needKey())return;if(project.boardStale){setError("剧本已修改，请先在「分镜」中按新剧本更新分镜。");setTab("panels");return;}
  const source=project;await run("准备绘制…",async()=>{
   let current=source;
   if(!current.reference||current.referenceStale){setBusy("正在绘制角色参考图…");current=await makeReference(current);if(stopRef.current)return;}
   const targets=index===undefined?current.panels.map((p,i)=>!p.image||p.stale?i:-1).filter(i=>i>=0):[index];
   setTab("comic");setProgress({done:0,total:targets.length});
   for(let k=0;k<targets.length;k++){
    if(stopRef.current)break;const i=targets[k];setBusy(`正在绘制第 ${i+1} 格，共 ${targets.length} 格待绘制…`);
    const result=imageResponseSchema.parse(await request({action:"image",style:current.style,characters:current.characters,panel:{title:current.panels[i].title,shot:current.panels[i].shot,scene:current.panels[i].scene,dialogue:current.panels[i].dialogue},reference:current.reference}));
    current={...current,panels:current.panels.map((p,j)=>i===j?{...p,image:result.image,stale:false}:p)};setProject(current);setProgress({done:k+1,total:targets.length});
   }
   if(stopRef.current)toast("已停止后续绘制，完成的画面已保留。");else toast.success(index===undefined?"漫画绘制完成":"这一格已重新绘制");
  });
 }
 // WebMCP reads the same visible project. No key or image payload is exposed.
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:object,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context)return;const lifecycle=new AbortController();
  const register=(tool:object)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register({name:"read_comic_project",description:"Read the current comic script, character descriptions and storyboard without credentials or images.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>{const p=projectRef.current;return p?{title:p.title,script:p.script,characters:p.characters,panels:p.panels.map(({title,shot,scene,dialogue,image,stale})=>({title,shot,scene,dialogue,hasImage:!!image,stale:!!stale}))}:{project:null};}});
  register({name:"navigate_comic_stage",description:"Open a stage of the visible comic editor. Does not generate content.",inputSchema:{type:"object",properties:{stage:{type:"string",enum:["script","characters","panels","comic"]}},required:["stage"],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(typeof input!=="object"||!input||!("stage" in input)||!stages.some(s=>s.id===input.stage))throw new Error("Invalid stage");setTab(input.stage as Tab);return{stage:input.stage};}});
  return()=>lifecycle.abort();
 },[]);
 const ready=!!project&&!project.boardStale&&loaded===project.panels.length;
 return <div className="studio"><Toaster position="bottom-right"/>
  <header className="topbar"><a className="brand" href="/"><span className="brand-icon"><Feather size={23}/></span><strong>漫想<small>COMIC STUDIO</small></strong></a><span className="top-caption">让故事，跃然纸上。</span><button className="secondary" disabled={!!busy} onClick={()=>{setDraftKey(key);setSettings(true);}}><Settings2 size={16}/>{key?"AI 已配置":"连接 AI"}</button></header>
  <main className="workspace"><aside className="story-sidebar">
   <div className="eyebrow">YOUR NEXT STORY</div><h1>每个想法，<br/>都值得一部漫画<span>。</span></h1><p className="intro">从一个念头开始，剩下的交给想象力。</p>
   <label className="field-label" htmlFor="story">你的故事 <span>01 / 灵感起点</span></label><div className="story-input"><textarea id="story" disabled={!!busy} value={story} onChange={e=>setStory(e.target.value)} placeholder="比如：一个怕黑的小女孩，在雨夜遇见一只会说话的邮差猫。它邀请她一起，把一封信送到月亮上……" maxLength={3000}/><span className="char-count">{story.length} / 3000</span></div>
   <button className="text-button" disabled={!!busy} onClick={loadSample}><Sparkles size={14}/>体验示例「雨夜邮差」</button>
   <fieldset disabled={!!busy}><legend className="field-label">选择画风</legend><RadioGroup className="style-options" value={style} onValueChange={setStyle} disabled={!!busy}>{styles.map((s,i)=><label key={s} className={style===s?"style-choice selected":"style-choice"}><RadioGroupItem value={s}/><span className={`style-swatch swatch-${i}`}>Aa</span><span>{s}</span>{style===s&&<Check size={13}/>}</label>)}</RadioGroup></fieldset>
   <fieldset disabled={!!busy}><legend className="field-label">漫画篇幅</legend><RadioGroup className="count-options" value={count} onValueChange={setCount} disabled={!!busy}>{["4","6","8"].map(n=><label key={n} className={n===count?"selected":""}><RadioGroupItem value={n}/>{n} 格<span>{n==="4"?"灵感短篇":n==="6"?"完整故事":"丰富叙事"}</span></label>)}</RadioGroup></fieldset>
   <button className="primary" disabled={!!busy} onClick={createPlan}>{busy?<LoaderCircle className="spin" size={17}/>:<WandSparkles size={17}/>}开始创作<ArrowRight size={17}/></button><p className="footnote">剧本 → 角色 → 分镜 → 漫画</p>
   {project&&<p className="sidebar-note">画风用于新作品。再次开始创作将替换当前方案，请先导出需要保留的内容。</p>}
   <div className="sidebar-bottom"><LockKeyhole size={14}/><span>内容仅在当前页面保留，离开前请导出。</span></div>
  </aside>
  <section className="editor" aria-busy={!!busy}><div className="editor-heading"><div><div className="eyebrow">CREATIVE WORKSPACE</div><h2>{project?.title||"故事创作台"}</h2></div><div className="heading-actions">{project&&<button className="icon-button" aria-label="导出剧本和分镜" title="导出剧本和分镜" disabled={!!busy} onClick={()=>exportScript(project)}><Download size={17}/></button>}<span className="badge">{project?(project.demo?"示例作品":`${project.panels.length} 格 · ${project.style}`):"新作品"}</span></div></div>
   {busy&&<div className="generation-status" role="status"><div><LoaderCircle size={16} className="spin"/><span>{busy}</span><button onClick={()=>{stopRef.current=true;toast("当前请求完成后停止后续绘制。");}} className="text-button">完成本次后停止</button></div>{progress&&<Progress value={progress.total?progress.done/progress.total*100:0} aria-label={`已完成 ${progress.done}/${progress.total} 格`}/>}<small>画面需要一些时间，已完成的内容会逐步显示。</small></div>}
   {error&&<div role="alert" className="error-banner">{error}<button aria-label="关闭错误提示" onClick={()=>setError("")}>×</button></div>}
   <Tabs value={tab} onValueChange={v=>setTab(v as Tab)}><TabsList className="workflow-tabs" variant="line">{stages.map(({id,label,Icon},i)=><TabsTrigger value={id} key={id}><span className="step-number">0{i+1}</span><Icon size={17}/>{label}</TabsTrigger>)}</TabsList>
    {!project?stages.map(({id})=><TabsContent key={id} value={id}><div className="empty-workspace"><div className="empty-symbol"><Feather size={38}/></div><div className="eyebrow">A LITTLE IDEA. A WHOLE NEW WORLD.</div><h3>你的下一部漫画，从这里开始</h3><p>写下一个故事，或从「雨夜邮差」开始。<br/>每一步都可以编辑，让想象按你的方式发生。</p><button className="sample-card" onClick={loadSample} disabled={!!busy}><img src="/sample-postcat.png" alt="黄色雨衣女孩与背着邮包的白猫在雨后小巷相遇"/><div><span className="eyebrow">从一场奇遇开始</span><strong>雨夜邮差</strong><span>体验示例 <ArrowRight size={14}/></span></div></button></div></TabsContent>):<>
    <TabsContent value="script"><div className="pane-content"><div className="pane-title"><div><h3>故事的骨架，想象的起点</h3><p>调整情节和对白，让故事更像你心中的模样。</p></div><BookOpen size={23}/></div><fieldset disabled={!!busy} className="editor-fields"><label>作品标题<input maxLength={180} value={project.title} onChange={e=>setProject({...project,title:e.target.value})}/></label><label>故事简介<textarea className="summary-input" maxLength={1200} value={project.summary} onChange={e=>setProject({...project,summary:e.target.value})}/></label><label>分幕剧本<textarea className="script-input" maxLength={8000} value={project.script} onChange={e=>setProject({...project,script:e.target.value,boardStale:true})}/></label></fieldset><div className="pane-footer"><span>{project.boardStale?"剧本已修改，请在分镜页更新画面安排。":"故事方案已就绪，接下来看看主角。"}</span><button className="primary" onClick={()=>setTab("characters")}>查看角色<ArrowRight size={16}/></button></div></div></TabsContent>
    <TabsContent value="characters"><div className="pane-content"><div className="pane-title"><div><h3>让主角，拥有自己的模样</h3><p>角色参考图将用于每一格绘制，帮助统一外观。</p></div><Users size={23}/></div><div className="character-list">{project.characters.map((c,i)=><fieldset key={i} disabled={!!busy} className="character-card"><div className="character-heading"><span className="character-number">0{i+1}</span><input aria-label={`角色${i+1}名称`} maxLength={180} value={c.name} onChange={e=>changeCharacter(i,"name",e.target.value)}/></div><label>身份<input maxLength={180} value={c.role} onChange={e=>changeCharacter(i,"role",e.target.value)}/></label><label>外貌与服装<textarea maxLength={1200} value={c.appearance} onChange={e=>changeCharacter(i,"appearance",e.target.value)}/></label><label>性格<textarea maxLength={600} value={c.personality} onChange={e=>changeCharacter(i,"personality",e.target.value)}/></label></fieldset>)}</div><div className="reference-section"><div><strong>角色参考图</strong><span>{project.referenceStale?"设定有修改，需要更新参考图。":"绘制漫画时会自动生成，也可以提前查看。"}</span></div>{project.reference&&<img src={project.reference} alt="所有角色的外观与服装参考图"/>}<button className="secondary" disabled={!!busy} onClick={referenceOnly}><WandSparkles size={16}/>{project.reference?"重新生成参考图":"生成角色参考图"}</button></div><div className="pane-footer"><span>修改角色设定后，已有画面会标记为待更新。</span><button className="primary" onClick={()=>setTab("panels")}>查看分镜<ArrowRight size={16}/></button></div></div></TabsContent>
    <TabsContent value="panels"><div className="pane-content"><div className="pane-title"><div><h3>把故事，拆成心动的瞬间</h3><p>编辑镜头、画面与对白。对白将独立排版，不烧录进图片。</p></div><Clapperboard size={23}/></div>{project.boardStale&&<div className="notice">剧本已有修改，请先更新分镜，再继续绘制。</div>}<div className="storyboard-actions"><span>当前 {project.panels.length} 格 · 更新后 {count} 格</span><button className="secondary" disabled={!!busy} onClick={rebreak}><RefreshCw size={14}/>按当前剧本更新分镜</button></div><p className="small-note">更新分镜会替换现有分镜及画面；失败时保留原作。</p><div className="panel-list">{project.panels.map((p,i)=><fieldset disabled={!!busy} className="panel-editor" key={i}><div className="panel-index">{String(i+1).padStart(2,"0")}<span>FRAME</span></div><div className="panel-fields"><div className="panel-row"><label>标题<input maxLength={180} value={p.title} onChange={e=>changePanel(i,"title",e.target.value)}/></label><label>镜头<input maxLength={180} value={p.shot} onChange={e=>changePanel(i,"shot",e.target.value)}/></label></div><label>画面描述<textarea maxLength={1600} value={p.scene} onChange={e=>changePanel(i,"scene",e.target.value)}/></label><label>对白 / 旁白<textarea className="dialogue-input" maxLength={400} value={p.dialogue} onChange={e=>changePanel(i,"dialogue",e.target.value)}/></label>{p.stale&&<span className="stale-label">画面描述有修改，待重新绘制</span>}</div></fieldset>)}</div><div className="pane-footer"><span>准备好后，就让角色走进画面。</span><button className="primary" disabled={!!busy||!!project.boardStale} onClick={()=>draw()}><WandSparkles size={16}/>绘制漫画</button></div></div></TabsContent>
    <TabsContent value="comic"><div className="pane-content"><div className="pane-title"><div><h3>故事，终于跃然纸上</h3><p>{project.demo?"示例仅首格附有插画，其余可连接 AI 继续绘制。":`${loaded} / ${project.panels.length} 格已就绪。满意的保留，想调整的单独重绘。`}</p></div><ImageIcon size={23}/></div><div className="comic-toolbar"><button className="secondary" disabled={!!busy||!ready} onClick={()=>run("正在导出漫画…",()=>exportComic(project))}><Download size={16}/>导出长图</button><button className="primary" disabled={!!busy||ready||!!project.boardStale} onClick={()=>draw()}><WandSparkles size={16}/>{loaded?"绘制剩余 / 更新画面":"一键绘制全部"}</button></div>{project.boardStale&&<div className="notice">请回到「分镜」，按修改后的剧本更新分镜。</div>}<div className="comic-grid">{project.panels.map((p,i)=><article className={`comic-panel ${p.stale?"is-stale":""}`} key={i}><div className="comic-art">{p.image?<img src={p.image} alt={p.scene}/>:<div className="undrawn"><ImageIcon size={25}/><strong>{p.title}</strong><span>等待绘制</span></div>}<span className="frame-number">{String(i+1).padStart(2,"0")}</span>{p.stale&&<span className="stale-stamp">待更新</span>}</div><p className="comic-dialogue">{p.dialogue||"（无对白）"}</p><div className="comic-panel-footer"><span>{p.shot}</span><button disabled={!!busy||!!project.boardStale} onClick={()=>draw(i)}><RefreshCw size={13}/>{p.image?"重绘这一格":"绘制这一格"}</button></div></article>)}</div><p className="small-note">角色参考图有助于统一外观；复杂动作和细节仍可能需要单格重绘。</p></div></TabsContent>
    </>}
   </Tabs>
  </section></main><footer className="page-footer"><span>漫想 · 把想象画出来</span><span>为故事而生，为创作者而做</span></footer>
  <Dialog open={settings} onOpenChange={setSettings}><DialogContent><DialogHeader><DialogTitle>连接你的 AI</DialogTitle><DialogDescription>填写 OpenAI API Key，即可创作新故事和绘制漫画。未连接时，也能体验和编辑示例。</DialogDescription></DialogHeader><form className="connection-form" onSubmit={e=>{e.preventDefault();if(draftKey.trim().length<20){toast.error("请输入有效的 API Key");return;}setKey(draftKey.trim());setDraftKey("");setSettings(false);toast.success("配置已保存到当前页面，将在生成时验证连接。");}}><label htmlFor="api-key">OpenAI API Key</label><input id="api-key" type="password" autoComplete="off" value={draftKey} onChange={e=>setDraftKey(e.target.value)} placeholder="sk-…" minLength={20} maxLength={500} required/><p>Key 仅保留在当前页面内存中，不写入浏览器存储；通过本站服务端转发至 OpenAI。生成内容也会发送给 OpenAI，按你的 API 账户计费。</p><div className="model-info"><span>剧本 / 分镜 <b>GPT-4.1 mini</b></span><span>角色 / 漫画 <b>GPT Image 1</b></span></div><div className="connection-actions">{key&&<button type="button" className="secondary" onClick={()=>{setKey("");setDraftKey("");setSettings(false);toast("已清除本页的 AI 配置");}}>断开连接</button>}<button className="primary" type="submit">保存配置<ArrowRight size={16}/></button></div></form></DialogContent></Dialog>
 </div>;
}
